// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qvVi9FmfVjNkS-zbe3THMNMtLaZhWy8',
    appId: '1:479942711865:web:767f8d805c3813d33acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    authDomain: 'phoneauth-d2c0e.firebaseapp.com',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    measurementId: 'G-0CPC4KL6RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw9vIYJcF4O4gTcmOxF-3p9OQD9ZgOafw',
    appId: '1:479942711865:android:5eb0ee7736226d083acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHho3sKgr-Mk2a9Dfc9HlA9OFSnIOEag',
    appId: '1:479942711865:ios:0809263c22353aa03acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    androidClientId: '479942711865-a7olfk4c15764pngcmpqd44969f7bfdl.apps.googleusercontent.com',
    iosClientId: '479942711865-n45i7qt509mpcbcn8smsn2734scs38iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHho3sKgr-Mk2a9Dfc9HlA9OFSnIOEag',
    appId: '1:479942711865:ios:0809263c22353aa03acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    androidClientId: '479942711865-a7olfk4c15764pngcmpqd44969f7bfdl.apps.googleusercontent.com',
    iosClientId: '479942711865-n45i7qt509mpcbcn8smsn2734scs38iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7qvVi9FmfVjNkS-zbe3THMNMtLaZhWy8',
    appId: '1:479942711865:web:6c95fdd8c9af22023acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    authDomain: 'phoneauth-d2c0e.firebaseapp.com',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    measurementId: 'G-QMKQBCHQWX',
  );
}
