// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qvVi9FmfVjNkS-zbe3THMNMtLaZhWy8',
    appId: '1:479942711865:web:e10644c7bad50ef03acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    authDomain: 'phoneauth-d2c0e.firebaseapp.com',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    measurementId: 'G-RD6WXSB1YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtc8HryfDwpHHgankk4Dc2syzSQXQzGFE',
    appId: '1:479942711865:android:3af0f4508b0333f23acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHho3sKgr-Mk2a9Dfc9HlA9OFSnIOEag',
    appId: '1:479942711865:ios:ec4462543a7219a23acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    androidClientId: '479942711865-9m0fb4o3p7j5k0vfttrcoga9o5d33iop.apps.googleusercontent.com',
    iosClientId: '479942711865-n45i7qt509mpcbcn8smsn2734scs38iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHho3sKgr-Mk2a9Dfc9HlA9OFSnIOEag',
    appId: '1:479942711865:ios:ec4462543a7219a23acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    androidClientId: '479942711865-9m0fb4o3p7j5k0vfttrcoga9o5d33iop.apps.googleusercontent.com',
    iosClientId: '479942711865-n45i7qt509mpcbcn8smsn2734scs38iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7qvVi9FmfVjNkS-zbe3THMNMtLaZhWy8',
    appId: '1:479942711865:web:f0cec88adcca87dc3acbe8',
    messagingSenderId: '479942711865',
    projectId: 'phoneauth-d2c0e',
    authDomain: 'phoneauth-d2c0e.firebaseapp.com',
    databaseURL: 'https://phoneauth-d2c0e-default-rtdb.firebaseio.com',
    storageBucket: 'phoneauth-d2c0e.firebasestorage.app',
    measurementId: 'G-SPW7FHMEMW',
  );
}
